custom:
  kmsSecrets: ${file(kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}
functions:
  challenge:
    events:
      - http:
          cors: true
          method: GET
          path: challenge/{id}/{token}
          request:
            parameters:
              paths:
                id: true
                token: true
    handler: handler.challenge
  challenge_open:
    handler: handler.challenge_open
  challenges:
    events:
      - http:
          cors: true
          method: GET
          path: challenges
    handler: handler.challenges
  challenges_set:
    handler: handler.challenges_set
  migrate:
    handler: handler.migrate
  ping:
    handler: handler.ping
  submit:
    events:
      - http:
          cors: true
          method: POST
          path: submit
    handler: handler.submit
  token:
    events:
      - http:
          cors: true
          method: POST
          path: token
    handler: handler.token
  user_confirm:
    events:
      - http:
          cors: true
          method: GET
          path: user_confirm/{id}
          request:
            parameters:
              paths:
                id: true
    handler: handler.user_confirm
  user_register:
    events:
      - http:
          cors: true
          method: POST
          path: user_register
    handler: handler.user_register
  users:
    handler: handler.users
package:
  exclude:
    - kms-secrets.*.us-east-2.yml
    - node_modules/**
    - package-lock.json
    - test*.py
    - "*.sh"
plugins:
  - serverless-kms-secrets
provider:
  environment:
    DB_HOST: dc2019q-scoreboard-${opt:stage, self:provider.stage}.cgwgx6ftjwg2.us-east-2.rds.amazonaws.com
    SECRETS: ${self:custom.kmsSecrets.secrets.SECRETS}
  iamRoleStatements:
    - Action:
      - KMS:Decrypt
      Effect: Allow
      Resource: ${self:custom.kmsSecrets.keyArn}
    - Action:
      - ses:SendEmail
      Effect: Allow
      Resource: "*"
  memorySize: 128
  name: aws
  profile: ooo
  region: us-east-2
  runtime: python3.6
  stage: dev
  vpc:
    securityGroupIds:
      - sg-0a863cf22c6690b80
    subnetIds:
      - subnet-0423499623e794a99
      - subnet-01108604635dcc775
      - subnet-0efdf26865a0f0c7e

service: dc2019q-scoreboard
